### ISSUE TITLE
invalid palette size in show_animation

### ISSUE THREAD

**Issue by hauswirth** [LuCEresearchlab/pytamaro#42]
The `show_animation` call in this code produces a **ValueError: invalid palette size**.

```python
radius = 200
frame1 = overlay(
    rotate(360 / 1, circular_sector(radius, 60, black)),
    rectangle(4 * radius, 2 * radius, red)
)
show_graphic(frame1)
frame2 = overlay(
    rotate(360 / 2, circular_sector(radius, 60, black)),
    rectangle(4 * radius, 2 * radius, red)
)
show_graphic(frame2)
show_animation([frame1, frame2])
```

Replacing `4 * radius` for both frames with `2 * radius` makes the error go away...

Also, with pytamaro 0.7.3 it used to work.

With pytamaro 1.1.0 on Python 3.13, it doesn't work (neither on the web site nor on the command line):

```sh
$ python --version
Python 3.13.0

$ pip list
Package     Version
----------- --------
numpy       2.2.0
pillow      11.0.0
pip         24.3.1
pybind11    2.13.6
pytamaro    1.1.0
skia-python 132.0b11

$ python err.py
Traceback (most recent call last):
  File "/Users/hauswirm/tmp/err.py", line 14, in <module>
    show_animation([frame1, frame2])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/pytamaro/io.py", line 271, in show_animation
    if _save_animation(file.name, graphics, duration, loop):
       ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/pytamaro/io.py", line 229, in _save_animation
    pil_images[0].save(
    ~~~~~~~~~~~~~~~~~~^
        filename,
        ^^^^^^^^^
    ...<4 lines>...
        disposal=2,  # 2 means "after showing the frame, clear to background"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/Image.py", line 2605, in save
    save_handler(self, fp, filename)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/GifImagePlugin.py", line 774, in _save_all
    _save(im, fp, filename, save_all=True)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/GifImagePlugin.py", line 787, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/GifImagePlugin.py", line 700, in _write_multiple_frames
    background_im.putpalette(im_frames[0].im.palette)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/Image.py", line 2103, in putpalette
    self.load()  # install new palette
    ~~~~~~~~~^^
  File "/Users/hauswirm/.pyenv/versions/pytamaro-1.1.0/lib/python3.13/site-packages/PIL/Image.py", line 909, in load
    self.im.putpalette(self.palette.mode, mode, arr)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid palette size
```

**Comment by lucach** [comment]
It's a [regression in Pillow 11.0](https://github.com/python-pillow/Pillow/issues/8493), funnily enough caused by the changes that were made to fix a bug _we_ reported. The bug has already been fixed, but Pillow adopts a quarterly release schedule. The next release is due at the beginning of the new year, after which we can update the dependency here.

**Comment by ArcasCZ** [comment]
Just a friendly reminder that the bug in Pillow should be fixed in 11.1.0

**Comment by lucach** [comment]
Yep, thanks! I've updated the dependency and released PyTamaro 1.1.2, which I can confirm solves this issue.
